# Site settings
title: Raees Khan - Ethical Hacker
description: Dynamic and highly motivated Ethical Hacker, ready to excel in cybersecurity.

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Navigation settings
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Skills
    url: /skills
  - title: Projects
    url: /projects
  - title: Education
    url: /education
  - title: Certifications
    url: /certifications
  - title: Contact
    url: /contact

# Social settings
social_icons:
  - title: LinkedIn
    url: https://www.linkedin.com/in/engr-raeeskhan/
    icon: fab fa-linkedin

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _config.yml
  - CNAME
  - .github
  - .vscode

# GitHub Pages settings
repository: rae3skhan/portfolio  # Replace with your actual repository name

# Customizations
custom_vars:
  location: "Ahingaro Dherai, Swat"
  email: "rae3skhan@gmail.com"
  phone: "+923427711179"
  profile_photo: "assets/your_photo_filename.jpg"  # Replace with your photo's filename

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
