# Site settings
title: Raees Khan - Ethical Hacker
description: Dynamic and highly motivated Ethical Hacker, ready to excel in cybersecurity.

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll

# Minimal Mistakes settings
minimal_mistakes_skin: default
minimal_mistakes_sidebar: left
minimal_mistakes_author: Raees Khan
minimal_mistakes_right_sidebar: false
minimal_mistakes_show_excerpts: true
minimal_mistakes_show_first_image: true

# Navigation settings
menu:
  # Sections: add/remove based on your content
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Skills
    url: /skills
  - title: Projects
    url: /projects
  - title: Education
    url: /education
  - title: Certifications
    url: /certifications
  - title: Contact
    url: /contact

# Social settings
social_icons:
  - title: LinkedIn
    url: https://www.linkedin.com/in/engr-raeeskhan/
    icon: fab fa-linkedin

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  
  - _config.yml
  - CNAME
  - .github
  - .vscode

# GitHub Pages settings
repository: rae3skhan/portfolio

# Customizations (optional)
# You can define custom site-wide variables and use them in your content
# Example:
custom_vars:
  location: "Ahingaro Dherai, Mingora, Swat, 19130"
  email: "rae3skhan@gmail.com"
  phone: "+923427711179"

# Jekyll plugins (optional)
# This example includes plugins for RSS feed and SEO optimization
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Add additional configurations depending on your projects and content
